# Generated by Django 5.2.4 on 2025-07-27 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_courseexam_coursereview_examanswer_examcertificate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('fundamentals', 'NCLEX-RN Fundamentals'), ('pharmacology', 'Pharmacology'), ('medical_surgical', 'Medical-Surgical'), ('pediatrics', 'Pediatrics'), ('obstetrics', 'Obstetrics & Gynecology'), ('psychiatric', 'Psychiatric Nursing'), ('community', 'Community Health'), ('leadership', 'Leadership & Management'), ('nursing', 'Nursing'), ('other', 'Other')], default='fundamentals', max_length=100),
        ),
    ]
