# Generated by Django 5.2.4 on 2025-07-30 13:48

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_total_duration_seconds_course_total_lessons_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='estimated_duration_hours',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated total course duration in hours', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='course',
            name='requirements',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), blank=True, default=list, help_text='List of requirements/prerequisites for this course', size=None),
        ),
        migrations.AddField(
            model_name='course',
            name='what_you_will_learn',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), blank=True, default=list, help_text='List of learning objectives/outcomes', size=None),
        ),
    ]
