# Generated by Django 5.2.4 on 2025-07-30 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_estimated_duration_hours_course_requirements_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='course',
            new_name='courses_categor_2870c7_idx',
            old_name='courses_categor_33f89e_idx',
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='courses.coursecategory'),
        ),
    ]
