# Generated by Django 5.2.4 on 2025-09-04 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_fix_array_fields_sqlite'),
    ]

    operations = [
    ]
