# Generated by Django 5.2.4 on 2025-09-04 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20250904_1258'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='course',
            new_name='courses_categor_2870c7_idx',
            old_name='courses_categor_33f89e_idx',
        ),
    ]
