# Generated by Django 5.2.4 on 2025-07-30 14:49

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_create_default_slug_all'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(courses.models.set_category_to_all), related_name='courses', to='courses.coursecategory'),
        ),
    ]
