# Generated by Django 5.2.4 on 2025-07-26 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorbankaccount',
            name='auto_payout_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='instructorbankaccount',
            name='last_verification_attempt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instructorbankaccount',
            name='verification_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='instructorbankaccount',
            name='verification_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='instructorbankaccount',
            name='verification_provider',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='instructorbankaccount',
            name='verified_account_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
