# Generated by Django 5.2.4 on 2025-08-29 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_instructorbankaccount_auto_payout_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional payment metadata'),
        ),
    ]
