# Generated by Django 5.2.4 on 2025-08-30 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorpayout',
            name='currency',
            field=models.CharField(choices=[('NGN', 'Nigerian Naira'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('GHS', 'Ghanaian Cedi'), ('KES', 'Kenyan Shilling'), ('ZAR', 'South African Rand')], default='NGN', max_length=3),
        ),
    ]
