# Generated by Django 5.2.4 on 2025-07-15 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
