# Generated by Django 5.2.4 on 2025-07-26 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='email_type',
            field=models.CharField(choices=[('verification', 'Email Verification'), ('password_reset', 'Password Reset'), ('login_alert', 'Login Alert'), ('new_device', 'New Device Login'), ('password_changed', 'Password Changed'), ('account_locked', 'Account Locked'), ('account_deletion_requested', 'Account Deletion Requested'), ('deletion_cancelled', 'Deletion Cancelled'), ('account_deleted', 'Account Deleted'), ('new_course_pending_review', 'New Course Pending Review'), ('course_approved', 'Course Approved'), ('course_rejected', 'Course Rejected'), ('course_suspended', 'Course Suspended'), ('instructor_suspended', 'Instructor Suspended'), ('instructor_payout', 'Instructor Payout'), ('high_revenue_alert', 'High Revenue Alert')], max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Course Creator/Instructor'), ('super_admin', 'Platform Administrator')], default='user', max_length=15),
        ),
    ]
