# Generated by Django 5.2.4 on 2025-07-26 22:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_phone_alter_emaillog_email_type_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='moderated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='moderated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='moderation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='moderation_status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='email_type',
            field=models.CharField(choices=[('verification', 'Email Verification'), ('password_reset', 'Password Reset'), ('login_alert', 'Login Alert'), ('new_device', 'New Device Login'), ('password_changed', 'Password Changed'), ('account_locked', 'Account Locked'), ('account_deletion_requested', 'Account Deletion Requested'), ('deletion_cancelled', 'Deletion Cancelled'), ('account_deleted', 'Account Deleted'), ('new_course_pending_review', 'New Course Pending Review'), ('course_approved', 'Course Approved'), ('course_rejected', 'Course Rejected'), ('course_suspended', 'Course Suspended'), ('instructor_suspended', 'Instructor Suspended'), ('instructor_payout', 'Instructor Payout'), ('high_revenue_alert', 'High Revenue Alert'), ('course_created_confirmation', 'Course Created Confirmation'), ('course_approved', 'Course Approved'), ('course_rejected', 'Course Rejected'), ('course_suspended', 'Course Suspended'), ('high_value_sale_notification', 'High Value Sale Notification'), ('new_course_pending_approval', 'New Course Pending Approval'), ('course_updated_review_required', 'Course Updated - Review Required')], max_length=40),
        ),
    ]
