# Generated by Django 5.2.4 on 2025-07-27 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_moderated_at_user_moderated_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
