# Generated by Django 5.2.4 on 2025-07-27 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_phone_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Course Creator/Instructor'), ('super_admin', 'Platform Administrator')], default='user', max_length=20),
        ),
    ]
