# Generated by Django 5.2.4 on 2025-09-04 11:57

import django.contrib.auth.models
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_change_id_to_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emaillog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='emailverificationtoken',
            name='user',
        ),
        migrations.RemoveField(
            model_name='loginattempt',
            name='user',
        ),
        migrations.RemoveField(
            model_name='passwordresettoken',
            name='user',
        ),
        migrations.RemoveField(
            model_name='refreshtoken',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usersession',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_email_4b85f2_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_role_0ace22_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_is_acti_847b48_idx',
        ),
        migrations.RemoveField(
            model_name='user',
            name='account_locked_until',
        ),
        migrations.RemoveField(
            model_name='user',
            name='deletion_requested_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='deletion_scheduled_for',
        ),
        migrations.RemoveField(
            model_name='user',
            name='moderated_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='moderated_by',
        ),
        migrations.RemoveField(
            model_name='user',
            name='two_factor_secret',
        ),
        migrations.AlterField(
            model_name='user',
            name='backup_codes',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='failed_login_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='user',
            name='moderation_reason',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='moderation_status',
            field=models.CharField(default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='password_changed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('instructor', 'Instructor'), ('student', 'Student')], default='student', max_length=20),
        ),
        migrations.DeleteModel(
            name='EmailLog',
        ),
        migrations.DeleteModel(
            name='EmailVerificationToken',
        ),
        migrations.DeleteModel(
            name='LoginAttempt',
        ),
        migrations.DeleteModel(
            name='PasswordResetToken',
        ),
        migrations.DeleteModel(
            name='RefreshToken',
        ),
        migrations.DeleteModel(
            name='UserSession',
        ),
    ]
